### ISSUE TITLE
usar el package listings para los listados

### ISSUE THREAD

**Issue by crguezl** [jjlabrador/TFG-SyTW#1]
Deberíamos usar el package `listings` para los listados de código. 
En el preambulo:

```
    \usepackage{listings}
    \lstset{language=Ruby}
    \lstset{
    escapeinside={\#(*}{*)}
    }
```

y luego cuando quieres poner un listado:

```
 \begin{lstlisting}
 chazam_eigenclass = class << Chazam; self; end
 \end{lstlisting}
```

Mira también la documentación en:
-  [http://www.ctan.org/tex-archive/macros/latex/contrib/listings/](http://www.ctan.org/tex-archive/macros/latex/contrib/listings/)
- [http://en.wikibooks.org/wiki/LaTeX/Source_Code_Listings](http://en.wikibooks.org/wiki/LaTeX/Source_Code_Listings)

**Comment by jjlabrador** [comment]
Hecho.
